### PR TITLE
ENH: slicer-build-base: Update to Slicer r25055 from 2016-05-07

### PR DESCRIPTION
**Pull request by jcfr**
```
$ git shortlog 953fce2..9296115 --no-merges
jcfr (9):
      STYLE: qMRMLSceneModel: clarify cast
      ENH: qSlicerCoreIOManager: Display time used to load a file.
      PERF: qMRMLSceneModel: Track and reuse index during populateScene
      COMP: qMRMLSceneModel: Fix -Woverloaded-virtual and add comment.
      PERF: qMRMLSceneDisplayableModel: Factor out constant display node lookup.
      COMP: Fix vtkObserverManagerTest1 fail in debug
      PERF: qMRMLSceneHierarchyModel: Refactor nodeIndex() function
      PERF: Improve selection node lookup
      ENH: Update ITK

lassoan (1):
      BUG: Removed memory leaks in Python method calls
```

### CODE REVIEW

**Comment by thewtex** [comment]
:100: Thanks!

**Comment by jcfr** [comment]
Thanks for integrating.

Note: I am locally building the images .. will push them on dockerhub when done. (Most likely on Monday .. with faster connection from the office)

**Comment by thewtex** [comment]
Cool.  I am also building locally, and I can push earlier if you would like. I already pushed a local fork earlier today that had an updated ITK.

**Comment by jcfr** [comment]
Perfetto

**Comment by thewtex** [comment]
Updated!

**Comment by jcfr** [comment]
Nice. Your connection faster than mine :8ball:

**Pull request merged**
