### PR TITLE
ENH: slicer-build-base: Update to Slicer r25079 from 2016-05-18

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Locally rebuilding. Will post comment when it succeed.

**Comment by jcfr** [comment]
```
Successfully built 874c13ab71f0
```

Good for integration

**Comment by thewtex** [comment]
:+1: Thanks!

**Comment by jcfr** [comment]
Just pushed `slicer-build-deps` and `slicer-build-base`. Now pushing `slicer-build` image to docker hub.

**Pull request merged**
