### PR TITLE
Add slicer/slicer-test:opengl image

### PR DESCRIPTION
**Pull request by MayeulChassagnard**
This image has been moved from Slicer to SlicerDocker for a better understanding

### CODE REVIEW

**Comment by MayeulChassagnard** [comment]
@thewtex I did some mistakes on the README file.. I'm sorry, I'm going to fix them quickly

**Comment by thewtex** [comment]
@MayeulChassagnard Sounds good. Otherwise the PR LGTM.

**Comment by MayeulChassagnard** [comment]
Nice, thanks!

Let me know when the image is pushed to try on my side to fix issues if there are some on Slicer's CircleCI.

**Comment by thewtex** [comment]
Thanks! Building...

**Comment by thewtex** [comment]
@MayeulChassagnard The *Dockerfile* needs some additions:

```
One or more build-args [BUILD_DATE IMAGE VCS_REF VCS_URL] were not consumed, failing build
```

**Comment by thewtex** [comment]
:+1: Thanks. Builds successfully. Will push after `master` branch builds successfully.

**Pull request merged**
