### PR TITLE
ENH: Add tests to the build tree in slicer-build docker image

### PR DESCRIPTION
**Pull request by MayeulChassagnard**
This is in order to run the tests at some point

CC: @thewtex

### CODE REVIEW

**Comment by thewtex** [comment]
@MayeulChassagnard Could you please create a new directory and configuration, `slicer-test` that has `BUILD_TESTING` `ON` and keep `BUILD_TESTING` `OFF` for `slicer-build`. This will allow extension builds to pull down the smaller `slicer-build` image and Slicer itself can use the `slicer-test` image. We could change the name of `slicer-build-deps` to `slicer-dependencies` to be more consistent also.

**Comment by MayeulChassagnard** [comment]
@thewtex I think we have to merge this branch before being able to know if circleCI works to run the tests of slicer

**Comment by MayeulChassagnard** [comment]
Updated & rebased [here](https://github.com/thewtex/SlicerDocker/pull/18) https://github.com/thewtex/SlicerDocker/pull/18

**Comment by thewtex** [comment]
Addressed in #18 and #19

**Pull request closed without merging**
